WebSubteEstadisticas/Models/BaseViewModel.cs
namespace WebSubteEstadisticas.Models
{
    public class BaseViewModel
    {
        public BaseViewModel()
        {
            Title = "Estadisticas subte";
        }

        public string Title { get; set; }
    }
}

WebSubteEstadisticas/Models/ErrorViewModel.cs
using System;

namespace WebSubteEstadisticas.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebSubteEstadisticas/Models/HomeViewModel.cs
namespace WebSubteEstadisticas.Models
{
    public class HomeViewModel : BaseViewModel
    {
      
    }
}

WebSubteEstadisticas/Models/Interno/TiempoFuncionamiento.cs
using Repository.Models;
using System;

namespace WebSubteEstadisticas.Models.Interno
{
    public class TiempoFuncionamiento
    {    
        private Precalculado Precalculo;

        public TiempoFuncionamiento(int minutosNormales, int minutosSuspendidos)
        {
          
        }

        public TiempoFuncionamiento(Precalculado datos)
        {            
            Precalculo = datos;
        }

        public double GetTiempoNormal
        {
            get
            {
                return Math.Round(TimeSpan.FromMinutes(Precalculo.MinutosNormal).TotalHours, 2);
            }
        }

        public double GetTiempoSuspendido
        {
            get
            {
                return Math.Round(TimeSpan.FromMinutes(Precalculo.MinutosSuspendida).TotalHours, 2);
            }
        }

        public double GetTiempoLimitada
        {
            get
            {
                return Math.Round(TimeSpan.FromMinutes(Precalculo.MinutosLimitada).TotalHours, 2);
            }
        }

        public double GetTiempoDemora
        {
            get
            {
                return Math.Round(TimeSpan.FromMinutes(Precalculo.MinutosDemora).TotalHours, 2);
            }
        }

        public double GetTiempoAnormales
        {
            get
            {
                return Math.Round(TimeSpan.FromMinutes(Precalculo.MinutosSuspendida + Precalculo.MinutosLimitada + Precalculo.MinutosDemora).TotalHours, 2);
            }
        }
    }
}

WebSubteEstadisticas/Controllers/Api/DataApiController.cs
using Microsoft.AspNetCore.Mvc;
using Repository;
using Repository.Models;
using System;
using System.Linq;
using WebSubteEstadisticas.Helper;

namespace WebSubteEstadisticas.Controllers.Api
{
    [Route("api/DataApi")]    
    public class DataApiController : ControllerBase
    {
        private Manager manager = new Manager(new subtedataContext());

        [HttpGet]
        public JsonResult GetDataBetweens(DateTime desde, DateTime hasta)
        {
            var aux = HelperGetDataPeriod.GetBetweenDates(manager, desde, hasta);

            return new JsonResult(new
            {
                Normal = aux.Select(x => x.GetTiempoNormal).ToArray(),
                Suspendida = aux.Select(x => x.GetTiempoSuspendido).ToArray(),
                Demora = aux.Select(x => x.GetTiempoDemora).ToArray(),
                Limitada = aux.Select(x => x.GetTiempoLimitada).ToArray(),
                Anormales = aux.Select(x => x.GetTiempoAnormales).ToArray()
            });
        }
    }
}

WebSubteEstadisticas/Controllers/Api/SubteStateApiController.cs
using HtmlAgilityPack;
using Microsoft.AspNetCore.Mvc;
using Repository.Common;
using System.Collections.Generic;
using System.Linq;

namespace WebSubteEstadisticas.Controllers.Api
{
    [Route("api/SubteStateApi")]    
    public class SubteStateApiController : ControllerBase
    {      

        [HttpGet]
        public JsonResult GetSubteState()
        {
            List<SubteStatus> ret = new List<SubteStatus>();

            HtmlWeb htmlWeb = new HtmlWeb();
            HtmlDocument doc = htmlWeb.Load("https://www.metrovias.com.ar");
            var tr = doc.DocumentNode.SelectNodes("//table[@class='table']/tbody/tr");

            foreach (var row in tr)
            {
                var cells = row.SelectNodes("./td");
                //Solo proceso los nodos TR que tiene 3 elementos TD, porque son las rows que me interesan en la tabla de estado
                if (cells.Count == 3)
                {
                    var status = new SubteStatus
                    {
                        //Solo me interesa la letra de la linea
                        Linea = cells[1].InnerText.Split(' ').Last(),
                        //Como el tag puede tener N clases solo me fijo que tenga una de las dos que me interesa si esta suspendido o normal
                        Status = (cells[2].GetClasses().First(x => x == "suspendido" || x == "normal")),
                        Text = HtmlEntity.DeEntitize(cells[2].SelectNodes("./div/span").Last().InnerText)
                    };
                    ret.Add(status);

                    //Si es la ultima linea de subte (no quiero incluir premetro y variantes) que termine de iterar
                    if (status.Linea == "H")
                        break;
                }
                
            }
            return new JsonResult(ret);
        }
    }
}

WebSubteEstadisticas/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using WebSubteEstadisticas.Models;

namespace WebSubteEstadisticas.Controllers
{
    public class HomeController : Controller
    {     
        public IActionResult Index()
        {
            var model = new HomeViewModel();          
            
            return View(model);
        }

        public IActionResult About()
        {
            var model = new HomeViewModel();         

            return View(model);
        }
    }
}

WebSubteEstadisticas/Views/Home/Index.cshtml
@model HomeViewModel


@section Scripts
	{

	<script type="text/javascript" src="@Url.Content("/js/Chart.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("/lib/bootstrap/dist/js/bootstrap-datepicker.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("/lib/bootstrap/dist/js/bootstrap-datepicker.es.js")"></script>

	<script>
		var chart;

		function GetFormatDate(date) { 
			return date.getFullYear() + "-" + (date.getMonth() + 1) + "-" + date.getDate();
		}

		function getData() {						
			var desde = GetFormatDate($('#fechaDesde').datepicker('getDate'));						
			var hasta = GetFormatDate($('#fechaHasta').datepicker('getDate'));	

			$.ajax({
				url: "@Url.Action("GetDataBetweens", "DataApi")",
				data: { Desde: desde, Hasta: hasta },
				success: function (data) {
					chart.data.datasets[0].data = data.normal;
					chart.data.datasets[1].data = data.anormales;
					chart.update();
				 },
				dataType: "json"
			});
		}

		$(function () {
			chart = NewInstanceChart("chart", 20);			
			$('#fechaDesde').datepicker({				
				language: 'es',
				autoclose: true
			});

			$('#fechaHasta').datepicker({				
				language: 'es',
				autoclose: true
			});

			var ayer = new Date();
			ayer.setDate(ayer.getDate() - 1);

			$('#fechaDesde').datepicker('update', ayer);
			$('#fechaHasta').datepicker('update', ayer);
			getData();
		});
	</script>

}

<div class="container" style="margin-top:10px">
	<div class="row">
		<div class='col-sm-3'>
			<div class="form-group">
				<label>Fecha Desde</label>
				<div class='input-group date' id='fechaDesde'>
					<input type='text' class="form-control" />
					<span class="input-group-addon">
						<span class="glyphicon glyphicon-calendar"></span>
					</span>
				</div>
			</div>
		</div>

		<div class='col-sm-3'>
			<div class="form-group">
				<label>Fecha Hasta</label>
				<div class='input-group date' id='fechaHasta'>
					<input type='text' class="form-control" />
					<span class="input-group-addon">
						<span class="glyphicon glyphicon-calendar"></span>
					</span>
				</div>
			</div>
		</div>

		<div class='col-sm-3'>
			<div class="form-group">
				<button onclick="getData()">Filtrar</button>
			</div>
		</div>
	</div>
	<div class="row">
		<div class='col-sm-8'>
			<div class="form-group">
				<canvas id="chart" width="400" height="400"></canvas>
			</div>
		</div>
	</div>
</div>

WebSubteEstadisticas/Views/Shared/_Layout.cshtml
@model BaseViewModel
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@Model.Title</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-controller="Home" asp-action="Index" class="navbar-brand">Estadisticas Subte</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-controller="Home" asp-action="Index">Inicio</a></li>
					<li><a asp-controller="Home" asp-action="About">Informacion</a></li>					
				</ul>
			</div>
		</div>
	</nav>
	<div class="container body-content">
		@RenderBody()				
	</div>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("Scripts", required: false)
</body>
</html>